apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: rajjejosefsson/multi-server # expect env variables :O, later
          ports:
            containerPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server # what we have server-deployment.yaml as label in template
  ports:
    - port: 5000 # the port for other Pods that needs multi-server pod
      targetPort: 5000  # the port server-deployment that the express server exposes to us


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: rajjejosefss/multi-client
          ports:
            - containerPort: 3000

---


apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web # what we have client-deployment.yaml as label in template
  ports:
    - port: 3000 # the port for other Pods that needs multi-client pod
      targetPort: 3000 # the port client-deployment need for our app