sudo: required

services:
  - docker
env:
    global:
      - SHA=$(git rev-parse HEAD)
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # don't show us any prompts

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # for google cloud
  - curl https://sdk.cloud.google.com | bash > /dev/null; # install gcloud it locally to travis
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json # AWS have IAM which is more or less equivalent to activate-service-account
  # those three below also should also  be called in google cloud terminal first time a cluster is created
  - gcloud config set project multi-k8s-296113 # we should
  - gcloud config set compute/zone europe-west1-b # same as in kubernets engine and cluster
  - gcloud container clusters get-credentials multi-k8s-cluster # operate on this cluster

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t rajjejosefsson/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true rajjejosefsson/react-test npm test


# travis don't support kubernetes deploy as docker aws
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main  # run only on main

