apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: rajjejosefsson/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: '.'
          - src: '**/*.css'
            dest: '.'
          - src: '**/*.html'
            dest: '.'

    - image: rajjejosefsson/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: '.'

    - image: rajjejosefsson/multi-worker
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: '.'
deploy:
  kubectl:
    manifests:
      - ./k8s/client-deployment.yaml
      - ./k8s/server-deployment.yaml
      - ./k8s/worker-deployment.yaml
      - ./k8s/client-cluster-ip-service.yaml
      - ./k8s/server-cluster-ip-service.yaml
portForward:
  - resourceType: deployment
    resourceName: client-deployment
    port: 3000
  - resourceType: deployment
    resourceName: server-deployment
    port: 5000